[package]
name = "mlz-small-language-model"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
ort = "2.0.0-rc.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1", features = ["full"] }
